services:
  connector:
    image: ghcr.io/nmshd/connector:6.16.1
    container_name: connector-with-custom-module
    ports:
      - "8080:80"
    environment:
      - CUSTOM_CONFIG_LOCATION=/config.json
      - transportLibrary__baseUrl
      - transportLibrary__platformClientId
      - transportLibrary__platformClientSecret
    volumes:
      - ./config.json:/config.json:ro
      - ./custom-module:/usr/app/node_modules/custom-module
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    hostname: mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    logging:
      driver: none

volumes:
  mongo_data:
